app = "osmcal"
primary_region = "ams"
kill_signal = "SIGINT"
kill_timeout = 5

[experimental]
  auto_rollback = true

[env]
  GUNICORN_WORKERS = "2"
  OSMCAL_PG_HOST = "osmcal-db2.flycast"
  OSMCAL_PROD = "true"
  PORT = "8080"
  WRITABLE_REGION = "ams"

[[services]]
  protocol = "tcp"
  internal_port = 8080
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

  [[services.http_checks]]
    interval = "10s"
    timeout = "2s"
    grace_period = "3s"
    restart_limit = 10
    method = "get"
    path = "/"
    protocol = "http"

[[statics]]
  guest_path = "/app/static/"
  url_prefix = "/static/"

[metrics]
  port = 8080
  path = "/metrics"

[deploy]
  release_command = "make migrate"
