app = "osmcal"

kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]
  PORT = "8080"
  OSMCAL_PROD = "true"
  GUNICORN_WORKERS = "2"

[experimental]
  allowed_public_ports = []
  auto_rollback = true
  private_network = true

[[services]]
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    handlers = ["http"]
    port = 80
    force_https = true

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.http_checks]]
    grace_period = "3s"
    interval = "10s"
    restart_limit = 10
    timeout = "2s"
    path = "/"
    method = "get"
    protocol = "http"

[[statics]]
  guest_path = "/app/static/"
  url_prefix = "/static/"

[metrics]
  port = 8080
  path = "/metrics"
