version: '3.8'

services:
  osmcal:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ../:/app
      - virtualenv:/root/.cache/pypoetry/virtualenvs:cached
    command: sleep infinity
    environment:
      - "OSMCAL_PG_HOST=db"
      - "OSMCAL_PG_PASSWORD=hunter2"

    network_mode: service:db

  db:
    image: postgis/postgis:15-3.4
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: osmcal
      POSTGRES_DB: osmcal
      POSTGRES_PASSWORD: hunter2

volumes:
  postgres-data:
  virtualenv:
